### ISSUE TITLE
Firmware dump

### ISSUE THREAD

**Issue by GianCann** [gpdaniels/spike-prime#1]
Hi @gpdaniels ,
Can you explain to me how to dump the Spike Prime Hub firmware?

**Comment by gpdaniels** [comment]
Sure.

To get a specific byte or bytes of the firmware:

1. I connected the Spike Prime Hub over a USB connection to my laptop.
2. Using a serial terminal you can access the REPL interface of the micropython firmware running on the hub.
3. Using the REPL interface if you run the following commands then it will print out a 32 bytes of the firmware.
```python
import firmware
firmware.flash_read(BYTE_NUMBER)
```

To dump the whole firmware I wrote a short program in C++ that performs the above sequence over and over again and saved the output. It would also possible to use python for this which at some point I'll get around to doing and add to this repo.

**Comment by GianCann** [comment]
Ok, but BYTE_NUMBER is not define.
Which is the corrispondent value? 32?

**Comment by gpdaniels** [comment]
It's the first byte you want to read.
So to get the first byte of the firmware (and the next 31 bytes), you'd call.
```python
firmware.flash_read(0)
```
Then to get the next 32 bytes you'd do.
```python
firmware.flash_read(32)
```
Continuing in 32 byte chunks until the function returns false.
```python
byte = 0
while True:
    if (firmware.flash_read(byte) == false):
        break;
    x += 32
```

**Comment by gpdaniels** [comment]
I've added new instructions to the readme that explain how to use the DFU mode to dump the firmware, which is probably easier.
