### ISSUE TITLE
Flashing Spike firmware onto MINDSTORMS hub

### ISSUE THREAD

**Issue by gabebear** [gpdaniels/spike-prime#14]
Do you know of any problems flashing a Spike firmware onto a 51515 hub? Is this thought to be a bad idea? (I haven’t tried it yet)

**Comment by postpersonality** [comment]
There is no problemswith that. I've flashed mine 51515 with Spike app and back with Robot Inventor app several times with no issues.

**Comment by gabebear** [comment]
Thanks!
