### ISSUE TITLE
[Question] Flash firmware to Spike Prime

### ISSUE THREAD

**Issue by cscovino** [gpdaniels/spike-prime#16]
Is there a way that I can flash firmware on the LEGO Spike Prime over serial communication? The idea is to update the firmware without the LEGO desktop app.
And the next question would be how I can get the updated firmware.

**Comment by gpdaniels** [comment]
You can use the dfu tool to do that.
Have a look at how pybricks are doing it. 

See:
- https://github.com/pybricks/pybricksdev
- https://github.com/pybricks/pybricksdev/blob/master/README_dfu.rst

I'm sure it's also possible using some of the functions in the `firmware` module in the SPIKE Prime.
I think there's some functions for reading and writing bytes of the flash, but I've not experimented with them.

**Comment by gpdaniels** [comment]
Regarding getting the updated firmware, I've been dumping the firmware of each release as they come.
So you can grab any of the firmwares from the [firmware](https://github.com/gpdaniels/spike-prime/tree/master/firmware) directory.
