### ISSUE TITLE
Problems with decompiler: container.sh 

### ISSUE THREAD

**Issue by ddrenteria** [gpdaniels/spike-prime#23]
Hi, I'm having a problem with the container.sh script that I didn't have before and a friend of mine is encountering the same problem. In the past the script used to work correctly but now it looks like is having some problems while initializing the builda.

![image](https://user-images.githubusercontent.com/54510442/124503018-09dbc800-dd9b-11eb-8f64-d0aaa0041715.png)

**Comment by gpdaniels** [comment]
I recommend that you use the python versions, I mainly developed the container script so that I could get a typescript environment working to allow me to port the typescript versions to python.

**Comment by ddrenteria** [comment]
Thx.
