### ISSUE TITLE
Add tech spec pdfs for new SPIKE Prime small hub and components.

### ISSUE THREAD

**Issue by gpdaniels** [gpdaniels/spike-prime#25]
- [ ] 45609 LEGO Technic Small Hub
- [ ] 45607 LEGO Technic Small Angular Motor
- [ ] 45608 LEGO Technic 3×3 Color Light Matrix
- [ ] 45612 LEGO Technic Small Hub Battery

**Comment by cscovino** [comment]
Here are the tech spec pdfs:

- [Spike Essential](https://education.lego.com/en-us/product-resources/45345-spike-essential-resource-page/downloads/technical-specifications)
- [Spike Prime](https://education.lego.com/en-us/product-resources/spike-prime/downloads/technical-specifications)
