### ISSUE TITLE
Decompiler output expectations?

### ISSUE THREAD

**Issue by MarkWard0110** [gpdaniels/spike-prime#29]
When I execute the decompile the decompiled .py files contain less than expected code.  Many of the files when I decompile them result in .py files containing output similar to the following `event_loop.py` where the file has imports, a declaration, then return none.

```import time
import utimeq
import collections
EventLoop = __build_class__(0, "EventLoop")
return None
```

Other files have lines like the following
```$push(__pop(__pop, 0))
$push(3)
BROKEN_OP`eq`
BROKEN_OP`btrue 147`
$push(hasattr(hub, "display"))
```
I was expecting to see more information like class, methods, variables, conditional statements, loops, etc.

Is the decompiler working as expected with the output I am getting?

**Comment by gpdaniels** [comment]
Closing as this is currently all that is expected of the decompiler.
