### ISSUE TITLE
Can you still write uncompiled programs?

### ISSUE THREAD

**Issue by CloudMracek** [gpdaniels/spike-prime#30]
Is it still possible to write uncompiled .py files like in the 1.0 firmware?
I'd like to write a program in micro-python and I want it to be launchable from the default menu. (Adding a program-picture etc.)

**Comment by gpdaniels** [comment]
No idea I'm afraid. I imagine you can add your own code to the `boot.py` file which I think runs first.
I'm not sure how you'd integrate what you create with the `*.mpy` files that are already there.
