### ISSUE TITLE
Connecting to Hub Failed! Opening COM8: File not found

### ISSUE THREAD

**Issue by ArshadIram** [gpdaniels/spike-prime#31]
Hello, First of all, thank you so much for this great plugin. I am trying to connect lego minestrone inventor with this plugin via VS code. Unfortunately, I am getting this Connecting to Hub Failed! Opening COM8: File not found. 

Can you please look into this issue?

![image](https://user-images.githubusercontent.com/50909488/158482971-0c1b64a1-4b40-49ce-a504-5bee7e371cb6.png)

**Comment by gpdaniels** [comment]
I think you've commented on the wrong repository?
