### ISSUE TITLE
Factory reset via hardware?

### ISSUE THREAD

**Issue by korggy** [gpdaniels/spike-prime#42]
I made the mistake of updating the firmware using the new SPIKE 3 software ... now I can't run my Python scripts, AND I can't reprogram back to the previous firmware! Yikes! Is there any way to revert to a previous firmware using a hardware reset?

**Comment by SpudGunMan** [comment]
Checkout the pybricks project on GitHub lots of firmware tools

**Comment by laurensvalk** [comment]
You could try this: https://dfu.pybricks.com/

**Comment by gpdaniels** [comment]
There's also this: 
https://legoeducation.atlassian.net/servicedesk/customer/portal/3/article/36816093261?src=1498125242&fbclid=IwAR2fxMGiLD1uTAnKIETnepYhH_xQ_cO5pGDKdUt7g4Fe0u7MHx2s5IbWES4

Which points to this tool:
https://spikelegacy.legoeducation.com/hubdowngrade/
