### ISSUE TITLE
Please add latest Spike Prime firmware

### ISSUE THREAD

**Issue by aivarannamaa** [gpdaniels/spike-prime#44]
The new firmware is supposed to have some significant changes at MicroPython level.

I only have the Robot Inventor hub, but the Spike app 3.0 won't update it. I've heard the Spike firmware does run on Robot Inventor.

**Comment by gpdaniels** [comment]
I've not updated the newest verion as I was waiting for LEGO to sort out programming in python for the device. Quoting their webpage:

> The Python API is part of a coming update to the SPIKE App.
> If you are coding in Python, we recommend you stay on the Spike Legacy App until this update is available.

**Comment by aivarannamaa** [comment]
The Python support should be back in version 3.2.4 of the app, but it needs to be enabled first. See https://www.youtube.com/watch?v=K-aQmM0Zshs

**Comment by aivarannamaa** [comment]
Since 3.3.0 the new Python API seems to be officially supported: https://legoeducation.atlassian.net/servicedesk/customer/portal/3/article/36995629060

**Comment by ktj** [comment]
@aivarannamaa have you had any luck trying the latest firmware in robot inventor hub?

**Comment by aivarannamaa** [comment]
> have you had any luck trying the latest firmware in robot inventor hub?

@ktj, no. My issue is that I don't know from where to get the latest firmware.

**Comment by gpdaniels** [comment]
I've added the firmware from update 3.3.1 which is the new type.
I'll look into getting the 3.4.0 firmware at some point in the future.
