### ISSUE TITLE
File corruption prevention missing

### ISSUE THREAD

**Issue by krisvih32** [gpdaniels/spike-prime#45]
my spike prime keeps corrupting the file and showing heads up could not open file

**Comment by gpdaniels** [comment]
I don't really understand what you're trying to do, and what is causing problems.

Flashing the backed up firmwares from here onto the hub is not tested, I'd recommend you look at https://pybricks.com/ if you want to do stuff like that.

**Comment by krisvih32** [comment]
It happened 3 times this week. Can you suggest a patch or an update. It is not just my computer that is broken. The llsp3 file got corrupted. I can rename it to zip and find the file though it is just an image. Can you suggest an image to llsp3 converter or should I set a recovery bit. What do you recommend?

**Comment by gpdaniels** [comment]
I've got no ideas. I've not explored that part of the system.
