### ISSUE TITLE
Create custom firmware for Robot Inventor?

### ISSUE THREAD

**Issue by mrdc** [gpdaniels/spike-prime#49]
Hi,

Is it possible to make a custom firmware for Robot Inventor? I want to embed some custom sounds, so they are played via built-in speaker and not via laptop/iPad etc.

Thanks!

**Comment by gpdaniels** [comment]
You should be able to push files onto the filesystem of the device and play them without needing an entire custom firmware. It'll probably have to be done in python rather than with blocks.

If you really want to go the custom firmware route check out https://pybricks.com/

**Comment by mrdc** [comment]
> If you really want to go the custom firmware route check out https://pybricks.com/

Thanks! Do you mean their [pybricks-micropython](https://github.com/pybricks/pybricks-micropython/tree/master) implementation? It's overkill for me, because only custom sounds are needed :D
