### ISSUE TITLE
Add official api docs

### ISSUE THREAD

**Issue by pitust** [gpdaniels/spike-prime#9]
Python lego mindstorms has some official docs. Could they be added here? (just pull them out of the apk)

**Comment by gpdaniels** [comment]
Sure the docs for each release could definitely be added here.
It'd be nice to see how they change between versions.

I'm not sure how to extract them from the Mindstorms apk, but I can probably extract them from the windows SPIKE Prime apps.

**Comment by pitust** [comment]
I know how to pull them out of the APK:
a) get split_asset_pack.apk
b) unpack `assets/webapp/static/knowledge`
c) you are done!

**Comment by gpdaniels** [comment]
From the SPIKE Prime apps the app.asar archive contains the reference under the path: `./app/renderer/static/knowledge/*`

**Comment by dlech** [comment]
Also see https://lego.github.io/MINDSTORMS-Robot-Inventor-hub-API/index.html

**Comment by gpdaniels** [comment]
Lego have done this for us! 

https://lego.github.io/MINDSTORMS-Robot-Inventor-hub-API/
